### ISSUE TITLE
[FEAT] Screenshot in the README

### ISSUE THREAD

**Issue by adityaraute** [nhcarrigan/timezone-chart#65]
# Feature Request

## Describe the solution you'd like
Add a screenshot in the README file for the users to know how simple and effective the website actually is

**Comment by nhcarrigan** [comment]
An issue with the _help wanted_ or _good first issue_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, please review our [contributing documentation](../blob/main/CONTRIBUTING.md).

If you have any issues with contributing, we are available to help in our [chat server](http://chat.nhcarrigan.com).

**Comment by sachinh19** [comment]
@nhcarrigan   I would like to submit a PR for this
