### ISSUE TITLE
[FEAT]: Add information on time and date format on the web page

### ISSUE THREAD

**Issue by sachinh19** [nhcarrigan/timezone-chart#68]
# Feature Request

## Is your feature request related to a problem? Please describe:

It is not clear from the website as to what time and date format has to be entered in the text boxes. It is confusing as I tried out epoch time, just military hours in time, then date+time and various formats until I found the correct one. It will enhance the user experience if there is no ambiguity.

## Describe the solution you'd like

This can be tackled in many different ways, simplest one would be to provide a info text with example on what needs to be entered in the date fields.

**Comment by nhcarrigan** [comment]
Does the input not include the placeholder and selection tool on your end?

![image](https://user-images.githubusercontent.com/63889819/109399747-86e0c780-78f9-11eb-965a-91bf068ba534.png)

**Comment by sachinh19** [comment]
I did not see this as I was using Firefox. Is this something specific to Chrome?

**Comment by sachinh19** [comment]
This is how it looks at my end.

![example](https://user-images.githubusercontent.com/34412458/109414494-01e0c700-7968-11eb-90fa-46f38b820e6d.png)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/109423341-de337600-7993-11eb-9a54-3776c91f8f54.png)

Ah, it seems Firefox doesn't support the `datetime-local` input type. We could potentially convert these in to standard input boxes and use a placeholder (or the label) to indicate the format.
